feat(typescript): convert core files to ts
ekino/node-logger pull request #31
Opened 2021-11-29 15:28 UTC by tienduy-nguyen

2022-07-27 12:18 UTC, pebie commented
@tienduy-nguyen, 
Now that we have to build the project, how did you plan to publish the build on npm. It seems that you have test it on your own npm registry. Could you explains how you did that ?

2022-07-27 12:26 UTC, tienduy-nguyen commented
> @tienduy-nguyen, Now that we have to build the project, how did you plan to publish the build on npm. It seems that you have test it on your own npm registry. Could you explains how you did that ?

Yes, I tested it in my own npm.

2022-07-27 16:03 UTC, pebie requested changes

2022-07-27 16:03 UTC, pebie commented on .gitignore
> +
Could you add `.vscode` please :)

2022-07-27 16:03 UTC, pebie commented on .npmignore
> +.editorconfig
Could you add `.vscode` please

2022-07-27 16:03 UTC, pebie commented on package.json
> +            "import": "./lib/wrapper.mjs",
To remove because import are not correct. See comment about bellow.

2022-07-27 16:03 UTC, pebie commented on src/global.d.ts
> +declare module 'prettyoutput'
Remove this file

2022-07-27 16:03 UTC, pebie commented on src/importer.js
> +/**
Remove this file and see export default bellow

2022-07-27 16:03 UTC, pebie commented on src/index.ts
> +export { outputAdapters, outputUtils, internals }
```suggestion
export * from "./definitions"
export * as outputUtils from "./output_utils"
export * as outputAdapters from "./output_adapters"

export default {
    createLogger,
    setLevel,
    setNamespaces,
    setOutput,
    setGlobalContext,
    id
}
```

No need to expose `internals`

2022-07-27 16:03 UTC, pebie commented on src/output_utils.ts
> +export const stringify = (log: Log): string => {
```suggestion
export declare const stringify: (log: Record<string,unknown>) => string;
```

2022-07-27 16:03 UTC, pebie commented on src/wrapper.mjs
> +import logger from './index.js'
Remove this file

2022-07-27 16:45 UTC, tienduy-nguyen commented on .gitignore
> +
Done!

2022-07-27 16:46 UTC, tienduy-nguyen commented on .npmignore
> +.editorconfig
Now, I use the field `files` in `package.json`, so I don't need this file anymore. I deleted it.

2022-07-27 16:46 UTC, tienduy-nguyen commented on package.json
> +            "import": "./lib/wrapper.mjs",
Done!

2022-07-27 16:46 UTC, tienduy-nguyen commented on src/global.d.ts
> +declare module 'prettyoutput'
Done!

2022-07-27 16:46 UTC, tienduy-nguyen commented on src/importer.js
> +/**
done!

2022-07-27 16:47 UTC, tienduy-nguyen commented on src/index.ts
> +export { outputAdapters, outputUtils, internals }
Thank you so much for helping me to resolve the problem of `import Logger from ...` with this solution `export default`

2022-07-27 16:47 UTC, tienduy-nguyen commented on src/output_utils.ts
> +export const stringify = (log: Log): string => {
Done!

2022-07-27 16:47 UTC, tienduy-nguyen commented on src/wrapper.mjs
> +import logger from './index.js'
Done!

2022-07-28 07:51 UTC, fthouraud commented
Thank you for your contribution @tienduy-nguyen.

If I may, this work should have been split into several PR to ease the review and track each issue.

Also, why do you replace ava with Jest? 🤔

2022-07-28 13:00 UTC, pebie commented
> If I may, this work should have been split into several PR to ease the review and track each issue.

What do you mean ? Split between test, core and build maybe ?

2022-07-28 14:00 UTC, pebie approved these changes

2022-07-28 15:27 UTC, tienduy-nguyen commented
> If I may, this work should have been split into several PR to ease the review and track each issue.
> What do you mean ? Split between test, core and build maybe ?

I thinks Fabien want to talk about the separation for steps: travisCI -> Github action, update dependencies, .....
- I tried did it before with 3 different PR, but after all, il will take so much more efforts and time to do the review. So I deleted other PR and put them all here

> Also, why do you replace ava with Jest? 🤔

Ava is very light, It's not too bad for an libary npm. But it's syntax is not too familiar. It demands more tools to work completely as sinon and nyc. And debug with `ava` is less simple.
Meanwhile, `Jest` is a really good tool. The features are complete. It's easy to use, syntaxe is really well known and familiar. And Jest has many improvements for the performance in recents version.

On another hand, we have a trouble with `ava` with Github action when we make the comparison the string with color.

So I think `Jest` is a good choice to replace `ava`.

2022-07-30 18:07 UTC, fthouraud commented
It should have been done sequentially to keep track of each major modification instead of only two commits covering a total rewrite of the lib, some addition, a new CI system, etc.

The advantage of AVA is especially that it is a lightweight test runner without bringing extra tooling. Also, the fact you're not familiar with the syntax a tool provides doesn't mean it has to be replaced. Regarding Jest's improvements, I'm pretty sure it is unnoticeable for such a small project. This change is purely motivated by your personal tastes instead of actual benefits for the library.

I can't speak for the problem you encountered but as long as AVA was working before I bet you looked in the wrong direction ;)

No hard feelings here, I'm glad you contributed but it should have been focused more on the library and its history.

2022-07-30 18:10 UTC, fthouraud commented
It also relates to this #26.

2022-07-31 18:31 UTC, tienduy-nguyen commented
> It should have been done sequentially to keep track of each major modification instead of only two commits covering a total rewrite of the lib, some addition, a new CI system, etc.
> 
> The advantage of AVA is especially that it is a lightweight test runner without bringing extra tooling. Also, the fact you're not familiar with the syntax a tool provides doesn't mean it has to be replaced. Regarding Jest's improvements, I'm pretty sure it is unnoticeable for such a small project. This change is purely motivated by your personal tastes instead of actual benefits for the library.
> 
> I can't speak for the problem you encountered but as long as AVA was working before I bet you looked in the wrong direction ;)
> 
> No hard feelings here, I'm glad you contributed but it should have been focused more on the library and its history.

OK, thank Fabien for clarifying them. I appreciate that. I'll take the modification.

2022-08-01 12:36 UTC, pebie commented
> It should have been done sequentially to keep track of each major modification instead of only two commits covering a total rewrite of the lib, some addition, a new CI system, etc.

Ok to split by commit but do multiple PRs seems to be complicated since migrate TS needs to rework eslint, node modules, ci/cd...

I understand this PR is hard to review so we can split it by commit :

- tests
- core
- tooling

Maybe

2022-08-01 15:39 UTC, fthouraud commented
Why should this be difficult?

This should be perfectly fine in this order:
- dependency upgrades,
- #26 & #27,
- #28.

The dependency upgrade could be included in one of the two MR, but if the code needs modifications, this should not be mixed up with other changes.

2022-08-04 12:15 UTC, tienduy-nguyen commented
> Why should this be difficult?
> 
> This should be perfectly fine in this order:
> 
> * dependency upgrades,
> * [Migrate CI to GitHub Actions #26](https://github.com/ekino/node-logger/issues/26) & [Support and test LTS Node #27](https://github.com/ekino/node-logger/issues/27),
> * [Migrato to TypeScript #28](https://github.com/ekino/node-logger/issues/28).
> 
> The dependency upgrade could be included in one of the two MR, but if the code needs modifications, this should not be mixed up with other changes.

Thank Fabien for your suggestion. 
So now I tried to separate in 3 different PR:
- Update dependencies: https://github.com/ekino/node-logger/pull/38
- Replace travisCi by github action and support Nodejs LTS: https://github.com/ekino/node-logger/pull/39
- Js to Ts (only core files): https://github.com/ekino/node-logger/pull/31

2022-11-07 16:46 UTC, fthouraud approved these changes
Thank you @tienduy-nguyen for your effort 🙏 This is much appreciated.

This should be included in a major release due to the number of changes and the impact on imports.

2022-11-07 17:06 UTC, merged